title: Noé Lira # your name (or website title) here
logo: "/images/foto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, Villahermosa, Tabasco, México.
  <br><br>
  Mi objetivo es ayudar a empresas y gobiernos locales a generar soluciones a partir del análisis de datos.
  <br><br>
  Tengo experiencia en administración pública, medios de comunicación, consultoría a gobiernos locales. Soy maestro en economía y gestión municipal por el CIECAS del Instituto Politécnico Nacional.
  <br><br>
  <a href="https://www.linkedin.com/in/hnlira/">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/CVLIRA.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
